--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
output_dir: output
ultraviolet_theme: "twilight"

# les langues
languages:
    - fr
    - en

# les formats de date en fonction de la langue
dateFormat:
    fr: "%d/%m/%Y"
    en: "%m/%d/%Y"

# le dictionnaire pour les mots communs
translations:
    langue: 
        fr: "langue"
        en: "language"
    liens:
        fr: "liens"
        en: "links"
    telecharger:
        fr: "télécharger"
        en: "download"
    nojsclickme:
        fr: "Javascript semble désactivé ;<br/> cliquez ici"
        en: "Javascript seems disabled <br/> click on me"
    suivant:
        fr: "suivant"
        en: "next"
    precedent:
        fr: "précédent"
        en: "previous"
    comment:
        fr: "commentaires"
        en: "comments"
    onlyin:
        fr: "Seulement en"
        en: "Only in"
    whatsthis:
        fr: "?"
        en: "?"
    loading:
        fr: "Chargement en cours..."
        en: "loading..."
    entirely_done_with:
        en: "Entirely done with"
        fr: "Site entièrement réalisé avec"
    and:
        en: "and"
        fr: "et"
    last_modified:
        en: "Last modified"
        fr: "dernière modification "
    copyright:
        en: "<a href=\"http://creativecommons.org/licenses/by-sa/2.5/deed.en\">Copyright©</a>"
        fr: "<a href=\"http://creativecommons.org/licenses/by-sa/2.5/deed.fr\">Droits de reproduction ©</a>"
    subscribe:
        en: "Subscribe"
        fr: "s'abonner"
